modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
mixinConfigs = "packagedhyper.mixins.json"
description = '''
${mod_description}
'''

[[mixins]]
config = "mixin.packagedhyper.json"