modLoader = "javafml"
loaderVersion = "[34,)"
license = "MIT"
issueTrackerURL = "https://github.com/TheLMiffy1111/PackagedAvaritia/issues"

[[mods]]
	modId = "packagedavaritia"
	version = "0@VERSION@"
	displayName = "PackagedAvaritia:Universal"
	description = "A PackagedAuto addon that adds Avaritia autocrafting."
	logoFile = "packagedavaritia.logo.png"
	authors = "TheLMiffy1111"
	displayURL = "https://www.curseforge.com/minecraft/mc-mods/packagedavaritia"

[[dependencies.packagedavaritia]]
	modId = "forge"
	versionRange = "[34,)"
	mandatory = true

[[dependencies.packagedavaritia]]
	modId = "packagedauto"
	versionRange = "[2.0.11,)"
	mandatory = true

[[dependencies.packagedavaritia]]
	modId = "avaritia"
	versionRange = "[2,)"
	mandatory = true
