modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"

[[mods]]
modId = "packagedhyper"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''
${mod_description}
'''

[[dependencies.packagedhyper]]
modId = "ae2"
mandatory = false
versionRange = "[15,)"
ordering = "NONE"
side = "BOTH"
